# Copyright 2020 Google Inc. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

__author__ = 'gerardofn@virustotal.com'

from PyQt5 import QtCore, QtGui, QtWidgets
from virustotal.vt_ida.ui import vtlogo

class Ui_panelUI(object):
    def setupUi(self, panelUI):
        panelUI.setObjectName("panelUI")
        panelUI.resize(1106, 1217)
        panelUI.setAutoFillBackground(False)
        panelUI.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(panelUI)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(panelUI)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabBar::tab { \n"
"border: 2px;\n"
"height: 20px;\n"
"width: 100%;\n"
"color: white;\n"
"background-color: rgb(248, 248, 248);\n"
"} \n"
"\n"
"QTabWidget::pane  { \n"
"border-left: 1px solid rgb(35, 61, 255);\n"
"border-right: 1px solid rgb(35, 61, 255);\n"
"border-bottom: 1px solid rgb(35, 61, 255);\n"
"border-top: 1px solid rgb(35, 61, 255);\n"
"}\n"
"\n"
"QTabBar::tab:selected { \n"
"color: white;\n"
"background-color: rgb(42, 45, 255);\n"
"border-left: 1px solid rgb(42, 45, 255);\n"
"border-right: 1px solid rgb(42, 45, 255);\n"
"border-top: 1px solid rgb(42, 45, 255);\n"
"border-bottom: 1px solid rgb(42, 45, 255);\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"color: black;\n"
"background-color: rgb(248, 248, 248);\n"
"border-left: 1px solid gray;\n"
"border-right: 1px solid gray;\n"
"border-top: 1px solid gray;\n"
"}\n"
"\n"
"QTabBarWidget::tab-bar {\n"
"color: black;\n"
"background-color: rgb(248, 248, 248);\n"
"border-bottom: 1px solid  rgb(35, 61, 255);\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_info = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_info.sizePolicy().hasHeightForWidth())
        self.tab_info.setSizePolicy(sizePolicy)
        self.tab_info.setObjectName("tab_info")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.tab_info)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.groupBox = QtWidgets.QGroupBox(self.tab_info)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.le_creationtime = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_creationtime.sizePolicy().hasHeightForWidth())
        self.le_creationtime.setSizePolicy(sizePolicy)
        self.le_creationtime.setText("")
        self.le_creationtime.setReadOnly(True)
        self.le_creationtime.setPlaceholderText("")
        self.le_creationtime.setObjectName("le_creationtime")
        self.gridLayout.addWidget(self.le_creationtime, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.le_fs = QtWidgets.QLineEdit(self.groupBox)
        self.le_fs.setText("")
        self.le_fs.setMaxLength(32900)
        self.le_fs.setReadOnly(True)
        self.le_fs.setPlaceholderText("")
        self.le_fs.setClearButtonEnabled(False)
        self.le_fs.setObjectName("le_fs")
        self.gridLayout.addWidget(self.le_fs, 3, 2, 1, 1)
        self.le_Sha256 = QtWidgets.QLineEdit(self.groupBox)
        self.le_Sha256.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.le_Sha256.setText("")
        self.le_Sha256.setReadOnly(True)
        self.le_Sha256.setPlaceholderText("")
        self.le_Sha256.setObjectName("le_Sha256")
        self.gridLayout.addWidget(self.le_Sha256, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.le_md5 = QtWidgets.QLineEdit(self.groupBox)
        self.le_md5.setText("")
        self.le_md5.setReadOnly(True)
        self.le_md5.setPlaceholderText("")
        self.le_md5.setObjectName("le_md5")
        self.gridLayout.addWidget(self.le_md5, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.le_ls = QtWidgets.QLineEdit(self.groupBox)
        self.le_ls.setText("")
        self.le_ls.setReadOnly(True)
        self.le_ls.setPlaceholderText("")
        self.le_ls.setObjectName("le_ls")
        self.gridLayout.addWidget(self.le_ls, 4, 2, 1, 1)
        self.le_la = QtWidgets.QLineEdit(self.groupBox)
        self.le_la.setText("")
        self.le_la.setPlaceholderText("")
        self.le_la.setObjectName("le_la")
        self.gridLayout.addWidget(self.le_la, 5, 2, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_16.addWidget(self.label_15)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.ratio_malicious = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(24)
        self.ratio_malicious.setFont(font)
        self.ratio_malicious.setTextFormat(QtCore.Qt.RichText)
        self.ratio_malicious.setScaledContents(False)
        self.ratio_malicious.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ratio_malicious.setObjectName("ratio_malicious")
        self.horizontalLayout_14.addWidget(self.ratio_malicious)
        self.ratio_slash = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(24)
        self.ratio_slash.setFont(font)
        self.ratio_slash.setStyleSheet("color: rgb(35, 61, 255);\n"
"")
        self.ratio_slash.setAlignment(QtCore.Qt.AlignCenter)
        self.ratio_slash.setObjectName("ratio_slash")
        self.horizontalLayout_14.addWidget(self.ratio_slash)
        self.ratio_total = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(24)
        self.ratio_total.setFont(font)
        self.ratio_total.setStyleSheet("color: rgb(35, 61, 255);")
        self.ratio_total.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ratio_total.setObjectName("ratio_total")
        self.horizontalLayout_14.addWidget(self.ratio_total)
        self.verticalLayout_19.addLayout(self.horizontalLayout_14)
        self.api_key_type = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.api_key_type.setFont(font)
        self.api_key_type.setStyleSheet("background-color: rgb(35, 61, 255);\n"
"color: #ffffffff;\n"
"border:20px;\n"
"border-left: 5px solid rgb(35, 61, 255);\n"
"border-right: 5px solid rgb(35, 61, 255);\n"
"border-bottom: 5px solid rgb(35, 61, 255);\n"
"border-top: 5px solid rgb(35, 61, 255);\n"
"")
        self.api_key_type.setObjectName("api_key_type")
        self.verticalLayout_19.addWidget(self.api_key_type, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_16.addLayout(self.verticalLayout_19)
        self.horizontalLayout_10.addLayout(self.verticalLayout_16)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.verticalLayout_20.addWidget(self.groupBox)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_info)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tw_tags = QtWidgets.QTableWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_tags.sizePolicy().hasHeightForWidth())
        self.tw_tags.setSizePolicy(sizePolicy)
        self.tw_tags.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tw_tags.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_tags.setProperty("showDropIndicator", False)
        self.tw_tags.setDragDropOverwriteMode(False)
        self.tw_tags.setAlternatingRowColors(True)
        self.tw_tags.setGridStyle(QtCore.Qt.SolidLine)
        self.tw_tags.setObjectName("tw_tags")
        self.tw_tags.setColumnCount(4)
        self.tw_tags.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_tags.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_tags.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_tags.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_tags.setHorizontalHeaderItem(3, item)
        self.tw_tags.horizontalHeader().setVisible(False)
        self.tw_tags.horizontalHeader().setStretchLastSection(True)
        self.tw_tags.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tw_tags)
        self.verticalLayout_15.addLayout(self.verticalLayout_2)
        self.verticalLayout_20.addWidget(self.groupBox_5)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(40, 12))
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tb_filenames = QtWidgets.QTextBrowser(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_filenames.sizePolicy().hasHeightForWidth())
        self.tb_filenames.setSizePolicy(sizePolicy)
        self.tb_filenames.setAcceptDrops(False)
        self.tb_filenames.setDocumentTitle("")
        self.tb_filenames.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.tb_filenames.setObjectName("tb_filenames")
        self.verticalLayout_3.addWidget(self.tb_filenames)
        self.verticalLayout_20.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 18000))
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tw_packersinfo = QtWidgets.QTableWidget(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_packersinfo.sizePolicy().hasHeightForWidth())
        self.tw_packersinfo.setSizePolicy(sizePolicy)
        self.tw_packersinfo.setProperty("showDropIndicator", False)
        self.tw_packersinfo.setDragDropOverwriteMode(False)
        self.tw_packersinfo.setAlternatingRowColors(True)
        self.tw_packersinfo.setGridStyle(QtCore.Qt.SolidLine)
        self.tw_packersinfo.setObjectName("tw_packersinfo")
        self.tw_packersinfo.setColumnCount(2)
        self.tw_packersinfo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_packersinfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_packersinfo.setHorizontalHeaderItem(1, item)
        self.tw_packersinfo.horizontalHeader().setCascadingSectionResizes(True)
        self.tw_packersinfo.horizontalHeader().setStretchLastSection(True)
        self.tw_packersinfo.verticalHeader().setVisible(False)
        self.tw_packersinfo.verticalHeader().setDefaultSectionSize(40)
        self.tw_packersinfo.verticalHeader().setMinimumSectionSize(40)
        self.verticalLayout_4.addWidget(self.tw_packersinfo)
        self.verticalLayout_20.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_info)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tb_community = QtWidgets.QTextBrowser(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_community.sizePolicy().hasHeightForWidth())
        self.tb_community.setSizePolicy(sizePolicy)
        self.tb_community.setObjectName("tb_community")
        self.gridLayout_2.addWidget(self.tb_community, 2, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.cb_select_source = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_select_source.setCurrentText("Comments")
        self.cb_select_source.setObjectName("cb_select_source")
        self.cb_select_source.addItem("")
        self.cb_select_source.addItem("")
        self.cb_select_source.addItem("")
        self.horizontalLayout_3.addWidget(self.cb_select_source)
        self.pb_prev_msg = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_prev_msg.setObjectName("pb_prev_msg")
        self.horizontalLayout_3.addWidget(self.pb_prev_msg)
        self.pb_next_msg = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_next_msg.setObjectName("pb_next_msg")
        self.horizontalLayout_3.addWidget(self.pb_next_msg)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_20.addWidget(self.groupBox_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pb_upload = QtWidgets.QPushButton(self.tab_info)
        self.pb_upload.setStyleSheet("")
        self.pb_upload.setObjectName("pb_upload")
        self.horizontalLayout_4.addWidget(self.pb_upload)
        self.pb_check = QtWidgets.QPushButton(self.tab_info)
        self.pb_check.setObjectName("pb_check")
        self.horizontalLayout_4.addWidget(self.pb_check)
        self.pb_report_main = QtWidgets.QPushButton(self.tab_info)
        self.pb_report_main.setObjectName("pb_report_main")
        self.horizontalLayout_4.addWidget(self.pb_report_main)
        self.pb_configuration = QtWidgets.QPushButton(self.tab_info)
        self.pb_configuration.setObjectName("pb_configuration")
        self.horizontalLayout_4.addWidget(self.pb_configuration)
        self.verticalLayout_20.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_info, "")
        self.tab_analysis = QtWidgets.QWidget()
        self.tab_analysis.setObjectName("tab_analysis")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab_analysis)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_analysis)
        self.groupBox_12.setFlat(True)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.groupBox_12)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_13.addWidget(self.label_16)
        self.cb_related = QtWidgets.QComboBox(self.groupBox_12)
        self.cb_related.setObjectName("cb_related")
        self.cb_related.addItem("")
        self.cb_related.addItem("")
        self.cb_related.addItem("")
        self.horizontalLayout_13.addWidget(self.cb_related)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.tw_related = QtWidgets.QTableWidget(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_related.sizePolicy().hasHeightForWidth())
        self.tw_related.setSizePolicy(sizePolicy)
        self.tw_related.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tw_related.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_related.setDragDropOverwriteMode(False)
        self.tw_related.setAlternatingRowColors(True)
        self.tw_related.setObjectName("tw_related")
        self.tw_related.setColumnCount(0)
        self.tw_related.setRowCount(0)
        self.tw_related.horizontalHeader().setCascadingSectionResizes(True)
        self.tw_related.horizontalHeader().setSortIndicatorShown(True)
        self.tw_related.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_18.addWidget(self.tw_related)
        self.verticalLayout_10.addLayout(self.verticalLayout_18)
        self.verticalLayout_17.addWidget(self.groupBox_12)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_analysis)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame = QtWidgets.QFrame(self.groupBox_7)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.cb_select_embedded = QtWidgets.QComboBox(self.frame)
        self.cb_select_embedded.setCurrentText("domains")
        self.cb_select_embedded.setObjectName("cb_select_embedded")
        self.cb_select_embedded.addItem("")
        self.cb_select_embedded.addItem("")
        self.cb_select_embedded.addItem("")
        self.horizontalLayout_5.addWidget(self.cb_select_embedded)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_8.addWidget(self.frame)
        self.tw_embedded = QtWidgets.QTableWidget(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_embedded.sizePolicy().hasHeightForWidth())
        self.tw_embedded.setSizePolicy(sizePolicy)
        self.tw_embedded.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tw_embedded.setAlternatingRowColors(True)
        self.tw_embedded.setShowGrid(True)
        self.tw_embedded.setGridStyle(QtCore.Qt.DashLine)
        self.tw_embedded.setCornerButtonEnabled(True)
        self.tw_embedded.setRowCount(0)
        self.tw_embedded.setObjectName("tw_embedded")
        self.tw_embedded.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tw_embedded.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_embedded.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_embedded.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_embedded.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_embedded.setHorizontalHeaderItem(4, item)
        self.tw_embedded.horizontalHeader().setVisible(False)
        self.tw_embedded.horizontalHeader().setCascadingSectionResizes(True)
        self.tw_embedded.horizontalHeader().setStretchLastSection(True)
        self.tw_embedded.verticalHeader().setVisible(False)
        self.verticalLayout_8.addWidget(self.tw_embedded)
        self.verticalLayout_17.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_analysis)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_2 = QtWidgets.QFrame(self.groupBox_8)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.cb_select_contacted = QtWidgets.QComboBox(self.frame_2)
        self.cb_select_contacted.setCurrentText("domains")
        self.cb_select_contacted.setObjectName("cb_select_contacted")
        self.cb_select_contacted.addItem("")
        self.cb_select_contacted.addItem("")
        self.cb_select_contacted.addItem("")
        self.horizontalLayout_6.addWidget(self.cb_select_contacted)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_9.addWidget(self.frame_2)
        self.tw_contacted = QtWidgets.QTableWidget(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_contacted.sizePolicy().hasHeightForWidth())
        self.tw_contacted.setSizePolicy(sizePolicy)
        self.tw_contacted.setAlternatingRowColors(True)
        self.tw_contacted.setObjectName("tw_contacted")
        self.tw_contacted.setColumnCount(3)
        self.tw_contacted.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_contacted.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_contacted.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_contacted.setHorizontalHeaderItem(2, item)
        self.tw_contacted.horizontalHeader().setCascadingSectionResizes(True)
        self.tw_contacted.horizontalHeader().setSortIndicatorShown(True)
        self.tw_contacted.horizontalHeader().setStretchLastSection(True)
        self.tw_contacted.verticalHeader().setVisible(False)
        self.verticalLayout_9.addWidget(self.tw_contacted)
        self.verticalLayout_17.addWidget(self.groupBox_8)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_analysis)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.groupBox_6)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.cb_select_sandbox = QtWidgets.QComboBox(self.frame_3)
        self.cb_select_sandbox.setCurrentText("")
        self.cb_select_sandbox.setObjectName("cb_select_sandbox")
        self.horizontalLayout_8.addWidget(self.cb_select_sandbox)
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.cb_select_sandbox_action = QtWidgets.QComboBox(self.frame_3)
        self.cb_select_sandbox_action.setCurrentText("")
        self.cb_select_sandbox_action.setObjectName("cb_select_sandbox_action")
        self.horizontalLayout_8.addWidget(self.cb_select_sandbox_action)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.tw_behaviour = QtWidgets.QTableWidget(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_behaviour.sizePolicy().hasHeightForWidth())
        self.tw_behaviour.setSizePolicy(sizePolicy)
        self.tw_behaviour.setAlternatingRowColors(True)
        self.tw_behaviour.setObjectName("tw_behaviour")
        self.tw_behaviour.setColumnCount(3)
        self.tw_behaviour.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_behaviour.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_behaviour.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_behaviour.setHorizontalHeaderItem(2, item)
        self.tw_behaviour.horizontalHeader().setCascadingSectionResizes(True)
        self.tw_behaviour.horizontalHeader().setSortIndicatorShown(True)
        self.tw_behaviour.horizontalHeader().setStretchLastSection(True)
        self.tw_behaviour.verticalHeader().setVisible(False)
        self.verticalLayout_6.addWidget(self.tw_behaviour)
        self.verticalLayout_17.addWidget(self.groupBox_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.pb_report_behaviour = QtWidgets.QPushButton(self.tab_analysis)
        self.pb_report_behaviour.setObjectName("pb_report_behaviour")
        self.horizontalLayout_7.addWidget(self.pb_report_behaviour)
        self.verticalLayout_17.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_analysis, "")
        self.tab_evidence = QtWidgets.QWidget()
        self.tab_evidence.setObjectName("tab_evidence")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_evidence)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_evidence)
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cb_select_source_2 = QtWidgets.QComboBox(self.groupBox_9)
        self.cb_select_source_2.setObjectName("cb_select_source_2")
        self.cb_select_source_2.addItem("")
        self.cb_select_source_2.addItem("")
        self.cb_select_source_2.addItem("")
        self.cb_select_source_2.addItem("")
        self.cb_select_source_2.addItem("")
        self.cb_select_source_2.addItem("")
        self.horizontalLayout_9.addWidget(self.cb_select_source_2)
        self.pb_search_code = QtWidgets.QPushButton(self.groupBox_9)
        self.pb_search_code.setObjectName("pb_search_code")
        self.horizontalLayout_9.addWidget(self.pb_search_code)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 0, 2, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.treew_evidence = QtWidgets.QTreeWidget(self.groupBox_9)
        self.treew_evidence.setMaximumSize(QtCore.QSize(571, 16777215))
        self.treew_evidence.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.treew_evidence.setAlternatingRowColors(True)
        self.treew_evidence.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.treew_evidence.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.treew_evidence.setUniformRowHeights(True)
        self.treew_evidence.setAnimated(True)
        self.treew_evidence.setWordWrap(True)
        self.treew_evidence.setObjectName("treew_evidence")
        item_0 = QtWidgets.QTreeWidgetItem(self.treew_evidence)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.treew_evidence.header().setCascadingSectionResizes(True)
        self.treew_evidence.header().setDefaultSectionSize(150)
        self.treew_evidence.header().setMinimumSectionSize(120)
        self.horizontalLayout_11.addWidget(self.treew_evidence)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.cb_selectall = QtWidgets.QCheckBox(self.groupBox_9)
        self.cb_selectall.setObjectName("cb_selectall")
        self.verticalLayout_12.addWidget(self.cb_selectall)
        self.pb_go_evidence = QtWidgets.QPushButton(self.groupBox_9)
        self.pb_go_evidence.setObjectName("pb_go_evidence")
        self.verticalLayout_12.addWidget(self.pb_go_evidence)
        self.pb_comment_evidence = QtWidgets.QPushButton(self.groupBox_9)
        self.pb_comment_evidence.setObjectName("pb_comment_evidence")
        self.verticalLayout_12.addWidget(self.pb_comment_evidence)
        self.pb_search_other_files = QtWidgets.QPushButton(self.groupBox_9)
        self.pb_search_other_files.setObjectName("pb_search_other_files")
        self.verticalLayout_12.addWidget(self.pb_search_other_files)
        self.pb_search_options = QtWidgets.QPushButton(self.groupBox_9)
        self.pb_search_options.setObjectName("pb_search_options")
        self.verticalLayout_12.addWidget(self.pb_search_options)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem9)
        self.horizontalLayout_11.addLayout(self.verticalLayout_12)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 1, 2, 1, 1)
        self.verticalLayout_13.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_evidence)
        self.groupBox_10.setFlat(True)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.tb_functions = QtWidgets.QTableWidget(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_functions.sizePolicy().hasHeightForWidth())
        self.tb_functions.setSizePolicy(sizePolicy)
        self.tb_functions.setMaximumSize(QtCore.QSize(573, 16777215))
        self.tb_functions.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tb_functions.setObjectName("tb_functions")
        self.tb_functions.setColumnCount(3)
        self.tb_functions.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_functions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_functions.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_functions.setHorizontalHeaderItem(2, item)
        self.tb_functions.horizontalHeader().setDefaultSectionSize(150)
        self.tb_functions.horizontalHeader().setMinimumSectionSize(120)
        self.tb_functions.verticalHeader().setVisible(False)
        self.horizontalLayout_12.addWidget(self.tb_functions)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pb_go_function = QtWidgets.QPushButton(self.groupBox_10)
        self.pb_go_function.setObjectName("pb_go_function")
        self.verticalLayout_14.addWidget(self.pb_go_function)
        self.pb_comment_function = QtWidgets.QPushButton(self.groupBox_10)
        self.pb_comment_function.setObjectName("pb_comment_function")
        self.verticalLayout_14.addWidget(self.pb_comment_function)
        self.pb_set_breakpoint = QtWidgets.QPushButton(self.groupBox_10)
        self.pb_set_breakpoint.setObjectName("pb_set_breakpoint")
        self.verticalLayout_14.addWidget(self.pb_set_breakpoint)
        self.pb_set_bookmark = QtWidgets.QPushButton(self.groupBox_10)
        self.pb_set_bookmark.setObjectName("pb_set_bookmark")
        self.verticalLayout_14.addWidget(self.pb_set_bookmark)
        self.pb_search_similar_functions = QtWidgets.QPushButton(self.groupBox_10)
        self.pb_search_similar_functions.setObjectName("pb_search_similar_functions")
        self.verticalLayout_14.addWidget(self.pb_search_similar_functions)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem10)
        self.horizontalLayout_12.addLayout(self.verticalLayout_14)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.verticalLayout_13.addWidget(self.groupBox_10)
        self.tabWidget.addTab(self.tab_evidence, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_11.addLayout(self.verticalLayout)

        self.retranslateUi(panelUI)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(panelUI)

    def retranslateUi(self, panelUI):
        _translate = QtCore.QCoreApplication.translate
        panelUI.setWindowTitle(_translate("panelUI", "VirusTotal"))
        self.groupBox.setAccessibleName(_translate("panelUI", "General"))
        self.label_8.setText(_translate("panelUI", "Last Submission:"))
        self.label_7.setText(_translate("panelUI", "First Submission:"))
        self.label_6.setText(_translate("panelUI", "Creation time:"))
        self.label.setText(_translate("panelUI", "MD5:"))
        self.label_2.setText(_translate("panelUI", "SHA-256:"))
        self.label_11.setText(_translate("panelUI", "Last analysis:"))
        self.label_15.setText(_translate("panelUI", "<html><head/><body><p><img src=\":/vtlogo/vt_logo.png\"/></p></body></html>"))
        self.ratio_malicious.setText(_translate("panelUI", "7"))
        self.ratio_slash.setText(_translate("panelUI", "/"))
        self.ratio_total.setText(_translate("panelUI", "60"))
        self.api_key_type.setText(_translate("panelUI", "COMMUNITY"))
        self.groupBox_5.setTitle(_translate("panelUI", "Tags"))
        item = self.tw_tags.horizontalHeaderItem(0)
        item.setText(_translate("panelUI", "New Column"))
        item = self.tw_tags.horizontalHeaderItem(1)
        item.setText(_translate("panelUI", "New Column"))
        item = self.tw_tags.horizontalHeaderItem(2)
        item.setText(_translate("panelUI", "New Column"))
        item = self.tw_tags.horizontalHeaderItem(3)
        item.setText(_translate("panelUI", "New Column"))
        self.groupBox_3.setTitle(_translate("panelUI", "File names submitted"))
        self.tb_filenames.setHtml(_translate("panelUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_4.setTitle(_translate("panelUI", "Packers and compilers"))
        self.tw_packersinfo.setSortingEnabled(True)
        item = self.tw_packersinfo.horizontalHeaderItem(0)
        item.setText(_translate("panelUI", "Tool"))
        item = self.tw_packersinfo.horizontalHeaderItem(1)
        item.setText(_translate("panelUI", "Detection"))
        self.groupBox_2.setTitle(_translate("panelUI", "Community"))
        self.tb_community.setHtml(_translate("panelUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_9.setText(_translate("panelUI", "Source:"))
        self.cb_select_source.setItemText(0, _translate("panelUI", "Comments"))
        self.cb_select_source.setItemText(1, _translate("panelUI", "Crowdsourced Sigma rules"))
        self.cb_select_source.setItemText(2, _translate("panelUI", "Crowdsourced Yara rules"))
        self.pb_prev_msg.setText(_translate("panelUI", "<"))
        self.pb_next_msg.setText(_translate("panelUI", ">"))
        self.pb_upload.setText(_translate("panelUI", "Upload to VT"))
        self.pb_check.setText(_translate("panelUI", "Check VT"))
        self.pb_report_main.setText(_translate("panelUI", "Open VTI report"))
        self.pb_configuration.setText(_translate("panelUI", "Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_info), _translate("panelUI", "Info"))
        self.groupBox_12.setTitle(_translate("panelUI", "Related samples"))
        self.label_16.setText(_translate("panelUI", "Select:"))
        self.cb_related.setItemText(0, _translate("panelUI", "compressed parents"))
        self.cb_related.setItemText(1, _translate("panelUI", "dropped files"))
        self.cb_related.setItemText(2, _translate("panelUI", "execution parents"))
        self.groupBox_7.setTitle(_translate("panelUI", "Embedded observables"))
        self.label_10.setText(_translate("panelUI", "Select:"))
        self.cb_select_embedded.setItemText(0, _translate("panelUI", "domains"))
        self.cb_select_embedded.setItemText(1, _translate("panelUI", "ip addresses"))
        self.cb_select_embedded.setItemText(2, _translate("panelUI", "urls"))
        self.tw_embedded.setSortingEnabled(True)
        item = self.tw_embedded.horizontalHeaderItem(0)
        item.setText(_translate("panelUI", "Observable"))
        item = self.tw_embedded.horizontalHeaderItem(1)
        item.setText(_translate("panelUI", "Detections"))
        item = self.tw_embedded.horizontalHeaderItem(2)
        item.setText(_translate("panelUI", "Scanned"))
        item = self.tw_embedded.horizontalHeaderItem(3)
        item.setText(_translate("panelUI", "Created"))
        item = self.tw_embedded.horizontalHeaderItem(4)
        item.setText(_translate("panelUI", "Country"))
        self.groupBox_8.setTitle(_translate("panelUI", "Contacted observables"))
        self.label_12.setText(_translate("panelUI", "Select:"))
        self.cb_select_contacted.setItemText(0, _translate("panelUI", "domains"))
        self.cb_select_contacted.setItemText(1, _translate("panelUI", "ip addresses"))
        self.cb_select_contacted.setItemText(2, _translate("panelUI", "urls"))
        item = self.tw_contacted.horizontalHeaderItem(0)
        item.setText(_translate("panelUI", "Observable"))
        item = self.tw_contacted.horizontalHeaderItem(1)
        item.setText(_translate("panelUI", "Detections"))
        item = self.tw_contacted.horizontalHeaderItem(2)
        item.setText(_translate("panelUI", "Created"))
        self.groupBox_6.setTitle(_translate("panelUI", "Behaviour"))
        self.label_13.setText(_translate("panelUI", "Sandbox:"))
        self.label_14.setText(_translate("panelUI", "Actions:"))
        item = self.tw_behaviour.horizontalHeaderItem(0)
        item.setText(_translate("panelUI", "Operation"))
        item = self.tw_behaviour.horizontalHeaderItem(1)
        item.setText(_translate("panelUI", "Name"))
        item = self.tw_behaviour.horizontalHeaderItem(2)
        item.setText(_translate("panelUI", "Value"))
        self.pb_report_behaviour.setText(_translate("panelUI", "Open VTI report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_analysis), _translate("panelUI", "Analysis"))
        self.groupBox_9.setTitle(_translate("panelUI", "Where to look for evidence:"))
        self.cb_select_source_2.setItemText(0, _translate("panelUI", "All"))
        self.cb_select_source_2.setItemText(1, _translate("panelUI", "Behaviour"))
        self.cb_select_source_2.setItemText(2, _translate("panelUI", "Contacted observables"))
        self.cb_select_source_2.setItemText(3, _translate("panelUI", "Dropped files"))
        self.cb_select_source_2.setItemText(4, _translate("panelUI", "Embedded observables"))
        self.cb_select_source_2.setItemText(5, _translate("panelUI", "File names submitted"))
        self.pb_search_code.setText(_translate("panelUI", "Search"))
        self.treew_evidence.setSortingEnabled(True)
        self.treew_evidence.headerItem().setText(0, _translate("panelUI", "Content"))
        self.treew_evidence.headerItem().setText(1, _translate("panelUI", "Address"))
        self.treew_evidence.headerItem().setText(2, _translate("panelUI", "Type"))
        __sortingEnabled = self.treew_evidence.isSortingEnabled()
        self.treew_evidence.setSortingEnabled(False)
        self.treew_evidence.topLevelItem(0).setText(0, _translate("panelUI", "Files dropped"))
        self.treew_evidence.topLevelItem(0).child(0).setText(0, _translate("panelUI", "popo.exe"))
        self.treew_evidence.topLevelItem(0).child(0).setText(1, _translate("panelUI", "67890"))
        self.treew_evidence.topLevelItem(0).child(0).setText(2, _translate("panelUI", "BYTE"))
        self.treew_evidence.topLevelItem(0).child(1).setText(0, _translate("panelUI", "pepe.exe"))
        self.treew_evidence.topLevelItem(0).child(1).setText(1, _translate("panelUI", "2345"))
        self.treew_evidence.topLevelItem(0).child(1).setText(2, _translate("panelUI", "ASCII"))
        self.treew_evidence.setSortingEnabled(__sortingEnabled)
        self.cb_selectall.setText(_translate("panelUI", "Select All"))
        self.pb_go_evidence.setText(_translate("panelUI", "Go"))
        self.pb_comment_evidence.setText(_translate("panelUI", "Auto comment"))
        self.pb_search_other_files.setText(_translate("panelUI", "Search other files"))
        self.pb_search_options.setText(_translate("panelUI", "Search options"))
        self.groupBox_10.setTitle(_translate("panelUI", "Used by the following code:"))
        item = self.tb_functions.horizontalHeaderItem(0)
        item.setText(_translate("panelUI", "Address"))
        item = self.tb_functions.horizontalHeaderItem(1)
        item.setText(_translate("panelUI", "Function name"))
        item = self.tb_functions.horizontalHeaderItem(2)
        item.setText(_translate("panelUI", "Segment"))
        self.pb_go_function.setText(_translate("panelUI", "Go"))
        self.pb_comment_function.setText(_translate("panelUI", "Auto comment"))
        self.pb_set_breakpoint.setText(_translate("panelUI", "Set breakpoint"))
        self.pb_set_bookmark.setText(_translate("panelUI", "Set bookmark"))
        self.pb_search_similar_functions.setText(_translate("panelUI", "Similar functions"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_evidence), _translate("panelUI", "Evidence"))
